### ISSUE TITLE
wax 202

### ISSUE THREAD

**Issue by sd95100** [rroller/netgear#12]
**Is your feature request related to a problem? Please describe.**
i have a wax 202 netgear. I tried to add it whith your embed but it tells me "Username, Password, or Address is wrong." I checked the passeword and ip address is good

**Describe the solution you'd like**
can you add the wax 202 please

![Sans titre](https://user-images.githubusercontent.com/67218839/168313863-a91e73e3-d8c7-4b50-bb4a-8bb8616b81aa.png)
![Sans titre](https://user-images.githubusercontent.com/67218839/168314143-4d48d9cb-6481-4941-b451-1f8df95394bc.png)

**Comment by apovadash** [comment]
Hi! i am an user of a WAX 214 and like with the wax202 there is no user prompt in our management web, using the default admin dont work

**Comment by psylou** [comment]
Same with WAX 206

**Comment by brentfamily51** [comment]
Having the same issue with WAX 218

Verified the device account name is admin but it's not a field for login, only the device password, so not sure if that impacts how the integration works or not.

**Comment by krothschild** [comment]
I have 4 of the WAX214 and when I try to add them, also get the "Username, Password, or Address is wrong." error. :-(

**Comment by klevin92** [comment]
Same hear. I would like to add my router but get an error

**Comment by lusciouslukey** [comment]
WAX206 here, also unable to use this integration.  I am not interested in figuring out why this does not work and acknowledge that this has not been sold as official  but I am really disappointed as thought I would be able to gain a little insight that I am currently lacking.  

With the official offering I actually get the same issue.  I am rejected upon installation setup as one of the items that I offered is incorrect.  The official and this fail to say which is wrong and that is probably because nothing entered on my side is incorrect, however, the information they ask for is not used to gain access so therefore incorrect.

I can't leave the username bit out or inform that only  the ip address and password are required for access.

**Comment by rroller** [comment]
Related to https://github.com/rroller/netgear/issues/14
Closing in favor of that. Please follow that one.

I'll need to get my hands on some of the hardware to reverse the auth flow
